


sentence_data = {
    "easy_sentence": [
        "The quick brown fox, with its swift and agile movements, effortlessly jumps over the lazy dog that is lying on the soft, green grass, enjoying a peaceful afternoon nap under the warm sunlight.",
        "A journey of a thousand miles, which might seem incredibly daunting at first, begins with the simple act of taking a single, determined step forward, symbolizing the power of perseverance and commitment.",
        "She sells seashells by the seashore, where the gentle waves crash against the sandy beach, and the salty sea breeze fills the air, making her quaint little shop a delightful place for tourists and locals alike.",
        "The early bird, eager and full of energy, catches the worm that wriggles in the dewy grass, demonstrating the advantages of rising early and seizing opportunities before others.",
        "A picture, with its vivid colors and intricate details, is worth a thousand words, as it can convey complex emotions and stories without the need for spoken or written language.",
        "Better late than never, they say, because arriving at a destination or completing a task, even if delayed, is more desirable than not showing up or finishing at all.",
        "Birds of a feather flock together, meaning that people with similar interests, values, or backgrounds tend to associate with each other, forming close-knit communities.",
        "Cleanliness is next to godliness, emphasizing the importance of maintaining a clean and orderly environment as a reflection of one's character and moral values.",
        "Don't bite the hand that feeds you, which is a reminder to be grateful and respectful to those who provide support or resources, as mistreating them can lead to negative consequences.",
        "Don't count your chickens before they hatch, advising against assuming the outcome of a situation before it actually happens, as plans can change unexpectedly.",
        "Easy come, easy go, highlighting the idea that things acquired with little effort are often lost just as easily, underscoring the value of hard work and persistence.",
        "Every cloud has a silver lining, suggesting that even in difficult or challenging situations, there is always a positive aspect or potential for something good to emerge.",
        "Haste makes waste, warning that rushing through tasks can lead to mistakes and inefficiency, advocating for a more careful and thoughtful approach to work.",
        "If it ain't broke, don't fix it, reminding us that unnecessary changes or interventions in a functioning system can cause more harm than good.",
        "It's always darkest before the dawn, meaning that difficult times often precede periods of improvement or success, encouraging perseverance and hope.",
        "Keep your friends close and your enemies closer, advising to maintain a close watch on adversaries to better understand their intentions and actions.",
        "Knowledge is power, emphasizing the value of education and information as tools for achieving success and making informed decisions.",
        "Laughter is the best medicine, suggesting that humor and joy can have a positive impact on mental and physical health.",
        "Let sleeping dogs lie, cautioning against interfering in situations that are currently calm or resolved, as it may cause unnecessary trouble.",
        "Look before you leap, advising to consider the potential consequences before taking action, to avoid regrettable mistakes.",
        "Money doesn't grow on trees, highlighting the importance of hard work and wise financial management, as resources are not unlimited.",
        "No man is an island, emphasizing the interconnectedness of people and the importance of community and relationships in achieving success and happiness.",
        "Practice makes perfect, reinforcing the idea that consistent effort and repetition are key to mastering skills and achieving excellence.",
        "Rome wasn't built in a day, reminding us that significant accomplishments take time and effort, and patience is essential for long-term success.",
        "Slow and steady wins the race, advocating for a consistent and measured approach to tasks, which can lead to better outcomes than rushing.",
        "The best things in life are free, suggesting that the most valuable experiences, such as love and happiness, cannot be bought with money.",
        "The pen is mightier than the sword, emphasizing the power of words and ideas over physical force in effecting change.",
        "There's no place like home, expressing the comfort and security that one's own home provides, which cannot be matched by other places.",
        "Time heals all wounds, indicating that emotional pain and difficulties often diminish with the passage of time.",
        "Two wrongs don't make a right, reminding that responding to a wrongdoing with another wrong action does not justify or resolve the situation.",
        "When the going gets tough, the tough get going, suggesting that strong and resilient people rise to challenges and continue to strive despite difficulties.",
        "You can't judge a book by its cover, advising against forming opinions based solely on appearances, as true value or character lies beneath the surface.",
        "Actions speak louder than words, highlighting that what people do is more significant and telling than what they say.",
        "Beggars can't be choosers, meaning that those in need must accept what is offered without complaint, as they are not in a position to be selective.",
        "Beauty is in the eye of the beholder, suggesting that perceptions of beauty are subjective and can vary greatly between individuals.",
        "A bird in the hand is worth two in the bush, emphasizing the value of a sure thing over the potential for something better that is uncertain.",
        "Break the ice, referring to the act of initiating conversation or activity to ease tension or awkwardness in social situations.",
        "Burning the midnight oil, describing the act of working late into the night to accomplish a task, often indicating dedication or urgency.",
        "Cat got your tongue? playfully asking someone why they are silent or reluctant to speak, often used to provoke a response.",
        "Curiosity killed the cat, warning that excessive inquisitiveness or prying can lead to trouble or danger.",
        "Don't put all your eggs in one basket, advising to diversify investments or efforts to mitigate risk.",
        "Every dog has its day, meaning that everyone experiences success or good fortune at some point in their life.",
        "Familiarity breeds contempt, suggesting that prolonged close association with someone or something can lead to a lack of respect or appreciation.",
        "Fortune favors the bold, encouraging taking risks and being courageous, as these qualities often lead to success.",
        "Get a taste of your own medicine, meaning to experience the same unpleasantness that one has inflicted on others.",
        "Give the benefit of the doubt, suggesting to assume good intentions or a positive outcome when there is uncertainty.",
        "Hit the nail on the head, meaning to precisely identify or address a problem or situation.",
        "In the heat of the moment, describing actions or decisions made impulsively due to strong emotions.",
        "It takes two to tango, indicating that cooperation or mutual effort is required to accomplish something or resolve an issue.",
        "Jump on the bandwagon, referring to the act of joining a trend or popular activity.",
        "Kill two birds with one stone, achieving two objectives with a single action.",
        "Let the cat out of the bag, accidentally revealing a secret or surprise.",
        "Make a long story short, summarizing or abbreviating a lengthy explanation.",
        "Miss the boat, failing to take advantage of an opportunity.",
        "No pain, no gain, suggesting that effort and suffering are necessary for achieving significant results.",
        "On the ball, indicating alertness and competence.",
        "Once in a blue moon, describing something that occurs very rarely.",
        "Piece of cake, referring to a task that is very easy to accomplish.",
        "Put the cart before the horse, doing things in the wrong order.",
        "Raining cats and dogs, describing very heavy rainfall.",
        "Saved by the bell, escaping a difficult situation just in time.",
        "Spill the beans, revealing secret information.",
        "Steal someone's thunder, taking credit for someone else's idea or achievement.",
        "Take it with a grain of salt, viewing something with skepticism.",
        "The ball is in your court, indicating that it is someone else's turn to take action.",
        "Throw caution to the wind, acting recklessly without concern for the consequences.",
        "Under the weather, feeling unwell or sick.",
        "When pigs fly, describing something that will never happen.",
        "You can't have your cake and eat it too, meaning you can't have it both ways.",
        "Your guess is as good as mine, indicating a lack of knowledge or certainty.",
        "A blessing in disguise, something that seems bad at first but has a good outcome.",
        "A dime a dozen, something very common or of little value.",
        "A leopard can't change its spots, meaning people can't change their true nature.",
        "Add insult to injury, making a bad situation worse.",
        "Bite off more than you can chew, taking on more than you can handle.",
        "Costs an arm and a leg, very expensive.",
        "Don't cry over spilt milk, don't waste time worrying about things that can't be changed.",
        "Hit the sack, going to bed to sleep.",
        "In the nick of time, at the last possible moment.",
        "It's not rocket science, something that is not difficult to understand.",
        "Let the chips fall where they may, allowing events to unfold naturally.",
        "Pull yourself together, gaining control of your emotions.",
        "Speak of the devil, referring to someone who appears just as they are being talked about.",
        "The last straw, the final problem in a series of problems that makes a situation unbearable.",
        "The whole nine yards, everything possible or available.",
        "Throw in the towel, giving up or quitting.",
        "To make a long story short, summarizing a lengthy explanation.",
        "Wouldn't be caught dead, never wanting to do something.",
        "A penny for your thoughts, asking someone what they are thinking about.",
        "An arm and a leg, something very expensive.",
        "Back to the drawing board, starting over again after a failed attempt.",
        "Beat around the bush, avoiding the main point.",
        "Bite the bullet, facing a difficult situation with courage.",
        "Break a leg, wishing someone good luck.",
        "Call it a day, stopping work for the day.",
        "Cut to the chase, getting to the point."
    ],

    "medium_sentence": [
        "To be or not to be, that is the question, pondered the troubled prince as he contemplated the profound complexities of life and the inevitable reality of death, seeking answers to his deepest existential dilemmas.",
        "All that glitters is not gold, a timeless reminder that appearances can be deceiving, and what may seem valuable on the surface might lack true worth upon closer inspection.",
        "Brevity is the soul of wit, suggesting that the essence of cleverness and intelligence lies in the ability to convey meaningful ideas concisely and effectively.",
        "A friend in need is a friend indeed, indicating that true friendship is demonstrated through support and assistance during difficult times, rather than just in moments of happiness.",
        "When in Rome, do as the Romans do, advising that one should adapt to the customs and behaviors of the place they are in, showing respect and willingness to integrate.",
        "The pen is mightier than the sword, emphasizing the power of written words and ideas to influence and effect change, often more significantly than physical force.",
        "A rolling stone gathers no moss, suggesting that a person who is always on the move or constantly changing jobs avoids responsibilities and long-term commitments.",
        "A stitch in time saves nine, meaning that addressing a problem early can prevent it from becoming more severe and complicated, saving effort and resources in the long run.",
        "Actions speak louder than words, highlighting that what people do is more significant and telling than what they say, revealing their true intentions and character.",
        "An apple a day keeps the doctor away, promoting the idea that maintaining healthy habits, such as eating nutritious foods, can contribute to overall well-being and prevent illness.",
        "As you sow, so shall you reap, indicating that one's actions and efforts, whether good or bad, will determine the results they experience in life.",
        "Better to have loved and lost than never to have loved at all, suggesting that the experience of love, despite its potential for pain, is more valuable than not experiencing it.",
        "Don't bite off more than you can chew, cautioning against taking on more tasks or responsibilities than one can handle, as it can lead to overwhelm and failure.",
        "Don't judge a book by its cover, advising against forming opinions based solely on appearances, as true value or character lies beneath the surface.",
        "Don't put the cart before the horse, warning against reversing the natural order of actions, as it can lead to confusion and inefficiency.",
        "Good things come to those who wait, encouraging patience and perseverance, as worthwhile achievements often require time and effort to come to fruition.",
        "Great minds think alike, suggesting that intelligent and creative people often come to similar conclusions or ideas, highlighting the value of shared wisdom.",
        "He who laughs last laughs longest, implying that ultimate success or satisfaction comes to those who remain patient and persistent, even in the face of initial setbacks.",
        "Honesty is the best policy, emphasizing the importance of truthfulness and integrity in building trust and maintaining healthy relationships.",
        "Hope for the best, prepare for the worst, advising a balanced approach of optimism and readiness for potential challenges, ensuring resilience and adaptability.",
        "If it ain't broke, don't fix it, reminding us that unnecessary changes or interventions in a functioning system can cause more harm than good.",
        "If you can't beat 'em, join 'em, suggesting that when facing strong opposition, it may be more effective to cooperate or align with them rather than continuing to resist.",
        "If you play with fire, you'll get burned, warning that engaging in risky or dangerous activities can lead to harmful consequences.",
        "In for a penny, in for a pound, indicating that once committed to a course of action, one should be prepared to see it through to the end, regardless of the cost.",
        "It's the tip of the iceberg, meaning that what is visible or known is only a small part of a much larger and often hidden issue or situation.",
        "Laughter is the best medicine, suggesting that humor and joy can have a positive impact on mental and physical health, promoting healing and well-being.",
        "Let bygones be bygones, advising to forget past disagreements or grievances and move forward without holding onto negative feelings.",
        "Like father, like son, indicating that children often inherit or learn the behaviors and traits of their parents, highlighting the influence of upbringing.",
        "Necessity is the mother of invention, suggesting that pressing needs or challenges often drive creative solutions and innovations.",
        "No news is good news, implying that the absence of information or updates often means that nothing bad has happened, offering a sense of relief.",
        "Once bitten, twice shy, meaning that experiencing a negative event makes one more cautious and wary in the future to avoid similar occurrences.",
        "Out of sight, out of mind, indicating that people or things that are not present are easily forgotten or overlooked.",
        "People who live in glass houses shouldn't throw stones, warning against criticizing others when one is vulnerable to similar criticism or faults.",
        "Practice what you preach, emphasizing the importance of acting in accordance with one's stated beliefs and principles.",
        "Silence is golden, suggesting that remaining quiet can be valuable, especially in situations where speaking may cause harm or unnecessary conflict.",
        "Strike while the iron is hot, advising to take advantage of favorable conditions or opportunities without delay, as they may not last.",
        "The early bird catches the worm, demonstrating the advantages of rising early and seizing opportunities before others.",
        "The grass is always greener on the other side, implying that people often believe others have it better, even if that perception is not accurate.",
        "The proof is in the pudding, meaning that the true value or quality of something can only be judged by putting it to the test.",
        "There's a method to the madness, suggesting that seemingly chaotic or irrational behavior has a logical purpose or underlying plan.",
        "There's no time like the present, encouraging immediate action rather than procrastination, as the current moment is the best time to start.",
        "Those who live by the sword, die by the sword, implying that a life of violence or aggression often leads to a violent end.",
        "Time waits for no one, emphasizing the relentless passage of time and the importance of making the most of every moment.",
        "Too many cooks spoil the broth, suggesting that too many people involved in a task can lead to confusion and poor results.",
        "Two heads are better than one, highlighting the benefits of collaboration and shared ideas in solving problems or making decisions.",
        "Variety is the spice of life, suggesting that diversity and new experiences make life more interesting and enjoyable.",
        "What goes around, comes around, indicating that actions, whether good or bad, often return to affect the person who initiated them.",
        "When in doubt, throw it out, advising to discard questionable items or ideas to avoid potential problems or risks.",
        "Where there's smoke, there's fire, suggesting that evidence of a problem often indicates a larger underlying issue.",
        "You can't have your cake and eat it too, meaning that one cannot enjoy both of two mutually exclusive options.",
        "You can't teach an old dog new tricks, implying that it is difficult to change established habits or behaviors.",
        "Your guess is as good as mine, indicating a lack of knowledge or certainty about a situation.",
        "A picture is worth a thousand words, suggesting that images can convey complex messages more effectively than words alone.",
        "An ounce of prevention is worth a pound of cure, emphasizing the importance of taking preventive measures to avoid bigger problems later.",
        "April showers bring May flowers, indicating that difficult times can lead to positive outcomes or growth.",
        "Birds of a feather flock together, meaning that people with similar interests, values, or backgrounds tend to associate with each other, forming close-knit communities.",
        "Cleanliness is next to godliness, emphasizing the importance of maintaining a clean and orderly environment as a reflection of one's character and moral values.",
        "Don't bite the hand that feeds you, which is a reminder to be grateful and respectful to those who provide support or resources, as mistreating them can lead to negative consequences.",
        "Don't count your chickens before they hatch, advising against assuming the outcome of a situation before it actually happens, as plans can change unexpectedly.",
        "Easy come, easy go, highlighting the idea that things acquired with little effort are often lost just as easily, underscoring the value of hard work and persistence.",
        "Every cloud has a silver lining, suggesting that even in difficult or challenging situations, there is always a positive aspect or potential for something good to emerge.",
        "Haste makes waste, warning that rushing through tasks can lead to mistakes and inefficiency, advocating for a more careful and thoughtful approach to work.",
        "If it ain't broke, don't fix it, reminding us that unnecessary changes or interventions in a functioning system can cause more harm than good.",
        "It's always darkest before the dawn, meaning that difficult times often precede periods of improvement or success, encouraging perseverance and hope.",
        "Keep your friends close and your enemies closer, advising to maintain a close watch on adversaries to better understand their intentions and actions.",
        "Knowledge is power, emphasizing the value of education and information as tools for achieving success and making informed decisions.",
        "Laughter is the best medicine, suggesting that humor and joy can have a positive impact on mental and physical health.",
        "Let sleeping dogs lie, cautioning against interfering in situations that are currently calm or resolved, as it may cause unnecessary trouble.",
        "Look before you leap, advising to consider the potential consequences before taking action, to avoid regrettable mistakes.",
        "Money doesn't grow on trees, highlighting the importance of hard work and wise financial management, as resources are not unlimited.",
        "No man is an island, emphasizing the interconnectedness of people and the importance of community and relationships in achieving success and happiness.",
        "Practice makes perfect, reinforcing the idea that consistent effort and repetition are key to mastering skills and achieving excellence.",
        "Rome wasn't built in a day, reminding us that significant accomplishments take time and effort, and patience is essential for long-term success.",
        "Slow and steady wins the race, advocating for a consistent and measured approach to tasks, which can lead to better outcomes than rushing.",
        "The best things in life are free, suggesting that the most valuable experiences, such as love and happiness, cannot be bought with money.",
        "The pen is mightier than the sword, emphasizing the power of words and ideas over physical force in effecting change.",
        "There's no place like home, expressing the comfort and security that one's own home provides, which cannot be matched by other places.",
        "Time heals all wounds, indicating that emotional pain and difficulties often diminish with the passage of time.",
        "Two wrongs don't make a right, reminding that responding to a wrongdoing with another wrong action does not justify or resolve the situation.",
        "When the going gets tough, the tough get going, suggesting that strong and resilient people rise to challenges and continue to strive despite difficulties.",
        "You can't judge a book by its cover, advising against forming opinions based solely on appearances, as true value or character lies beneath the surface.",
        "Actions speak louder than words, highlighting that what people do is more significant and telling than what they say.",
        "Beggars can't be choosers, meaning that those in need must accept what is offered without complaint, as they are not in a position to be selective.",
        "Beauty is in the eye of the beholder, suggesting that perceptions of beauty are subjective and can vary greatly between individuals.",
        "A bird in the hand is worth two in the bush, emphasizing the value of a sure thing over the potential for something better that is uncertain.",
        "Break the ice, referring to the act of initiating conversation or activity to ease tension or awkwardness in social situations.",
        "Burning the midnight oil, describing the act of working late into the night to accomplish a task, often indicating dedication or urgency.",
        "Cat got your tongue? playfully asking someone why they are silent or reluctant to speak, often used to provoke a response.",
        "Curiosity killed the cat, warning that excessive inquisitiveness or prying can lead to trouble or danger.",
        "Don't put all your eggs in one basket, advising to diversify investments or efforts to mitigate risk.",
        "Every dog has its day, meaning that everyone experiences success or good fortune at some point in their life.",
        "Familiarity breeds contempt, suggesting that prolonged close association with someone or something can lead to a lack of respect or appreciation.",
        "Fortune favors the bold, encouraging taking risks and being courageous, as these qualities often lead to success.",
        "Get a taste of your own medicine, meaning to experience the same unpleasantness that one has inflicted on others.",
        "Give the benefit of the doubt, suggesting to assume good intentions or a positive outcome when there is uncertainty.",
        "Hit the nail on the head, meaning to precisely identify or address a problem or situation.",
        "In the heat of the moment, describing actions or decisions made impulsively due to strong emotions.",
        "It takes two to tango, indicating that cooperation or mutual effort is required to accomplish something or resolve an issue.",
        "Jump on the bandwagon, referring to the act of joining a trend or popular activity.",
        "Kill two birds with one stone, achieving two objectives with a single action.",
        "Let the cat out of the bag, accidentally revealing a secret or surprise.",
        "Make a long story short, summarizing or abbreviating a lengthy explanation.",
        "Miss the boat, failing to take advantage of an opportunity.",
        "No pain, no gain, suggesting that effort and suffering are necessary for achieving significant results.",
        "On the ball, indicating alertness and competence.",
        "Once in a blue moon, describing something that occurs very rarely.",
        "Piece of cake, referring to a task that is very easy to accomplish.",
        "Put the cart before the horse, doing things in the wrong order.",
        "Raining cats and dogs, describing very heavy rainfall.",
        "Saved by the bell, escaping a difficult situation just in time.",
        "Spill the beans, revealing secret information.",
        "Steal someone's thunder, taking credit for someone else's idea or achievement.",
        "Take it with a grain of salt, viewing something with skepticism.",
        "The ball is in your court, indicating that it is someone else's turn to take action.",
        "Throw caution to the wind, acting recklessly without concern for the consequences.",
        "Under the weather, feeling unwell or sick.",
        "When pigs fly, describing something that will never happen.",
        "You can't have your cake and eat it too, meaning you can't have it both ways.",
        "Your guess is as good as mine, indicating a lack of knowledge or certainty.",
        "A blessing in disguise, something that seems bad at first but has a good outcome.",
        "A dime a dozen, something very common or of little value.",
        "A leopard can't change its spots, meaning people can't change their true nature.",
        "Add insult to injury, making a bad situation worse.",
        "Bite off more than you can chew, taking on more than you can handle.",
        "Costs an arm and a leg, very expensive.",
        "Don't cry over spilt milk, don't waste time worrying about things that can't be changed.",
        "Hit the sack, going to bed to sleep.",
        "In the nick of time, at the last possible moment.",
        "It's not rocket science, something that is not difficult to understand.",
        "Let the chips fall where they may, allowing events to unfold naturally.",
        "Pull yourself together, gaining control of your emotions.",
        "Speak of the devil, referring to someone who appears just as they are being talked about.",
        "The last straw, the final problem in a series of problems that makes a situation unbearable.",
        "The whole nine yards, everything possible or available.",
        "Throw in the towel, giving up or quitting.",
        "To make a long story short, summarizing a lengthy explanation.",
        "Wouldn't be caught dead, never wanting to do something.",
        "A penny for your thoughts, asking someone what they are thinking about.",
        "An arm and a leg, something very expensive.",
        "Back to the drawing board, starting over again after a failed attempt.",
        "Beat around the bush, avoiding the main point.",
        "Bite the bullet, facing a difficult situation with courage.",
        "Break a leg, wishing someone good luck.",
        "Call it a day, stopping work for the day.",
        "Cut to the chase, getting to the point."
    ],

    "hard_sentence": [
        "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.",
        "To be, or not to be, that is the question—whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and, by opposing, end them.",
        "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off—then, I account it high time to get to sea as soon as I can.",
        "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.",
        "In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, 'Let there be light,' and there was light. God saw that the light was good, and he separated the light from the darkness. God called the light 'day,' and the darkness he called 'night.' And there was evening, and there was morning—the first day.",
        "It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known.",
        "Two households, both alike in dignity, in fair Verona, where we lay our scene, from ancient grudge break to new mutiny, where civil blood makes civil hands unclean. From forth the fatal loins of these two foes, a pair of star-cross'd lovers take their life; whose misadventured piteous overthrows do with their death bury their parents' strife. The fearful passage of their death-mark'd love, and the continuance of their parents' rage, which, but their children's end, nought could remove, is now the two hours' traffic of our stage; the which if you with patient ears attend, what here shall miss, our toil shall strive to mend.",
        "All animals are equal, but some animals are more equal than others.",
        "It was a bright cold day in April, and the clocks were striking thirteen. The Ministry of Truth—Minitrue, in Newspeak—was startlingly different from any other object in sight. It was an enormous pyramidal structure of glittering white concrete, soaring up, terrace after terrace, three hundred meters into the air.",
        "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.",
        "To be, or not to be, that is the question—whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and, by opposing, end them.",
        "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off—then, I account it high time to get to sea as soon as I can.",
        "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.",
        "In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, 'Let there be light,' and there was light. God saw that the light was good, and he separated the light from the darkness. God called the light 'day,' and the darkness he called 'night.' And there was evening, and there was morning—the first day.",
        "It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known.",
        "Two households, both alike in dignity, in fair Verona, where we lay our scene, from ancient grudge break to new mutiny, where civil blood makes civil hands unclean. From forth the fatal loins of these two foes, a pair of star-cross'd lovers take their life; whose misadventured piteous overthrows do with their death bury their parents' strife. The fearful passage of their death-mark'd love, and the continuance of their parents' rage, which, but their children's end, nought could remove, is now the two hours' traffic of our stage; the which if you with patient ears attend, what here shall miss, our toil shall strive to mend.",
        "All animals are equal, but some animals are more equal than others.",
        "It was a bright cold day in April, and the clocks were striking thirteen. The Ministry of Truth—Minitrue, in Newspeak—was startlingly different from any other object in sight. It was an enormous pyramidal structure of glittering white concrete, soaring up, terrace after terrace, three hundred meters into the air.",
        "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.",
        "To be, or not to be, that is the question—whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and, by opposing, end them.",
        "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off—then, I account it high time to get to sea as soon as I can.",
        "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.",
        "In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, 'Let there be light,' and there was light. God saw that the light was good, and he separated the light from the darkness. God called the light 'day,' and the darkness he called 'night.' And there was evening, and there was morning—the first day.",
        "It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known.",
        "Two households, both alike in dignity, in fair Verona, where we lay our scene, from ancient grudge break to new mutiny, where civil blood makes civil hands unclean. From forth the fatal loins of these two foes, a pair of star-cross'd lovers take their life; whose misadventured piteous overthrows do with their death bury their parents' strife. The fearful passage of their death-mark'd love, and the continuance of their parents' rage, which, but their children's end, nought could remove, is now the two hours' traffic of our stage; the which if you with patient ears attend, what here shall miss, our toil shall strive to mend.",
        "All animals are equal, but some animals are more equal than others.",
        "It was a bright cold day in April, and the clocks were striking thirteen. The Ministry of Truth—Minitrue, in Newspeak—was startlingly different from any other object in sight. It was an enormous pyramidal structure of glittering white concrete, soaring up, terrace after terrace, three hundred meters into the air.",
        "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.",
        "To be, or not to be, that is the question—whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and, by opposing, end them.",
        "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off—then, I account it high time to get to sea as soon as I can.",
        "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.",
        "In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, 'Let there be light,' and there was light. God saw that the light was good, and he separated the light from the darkness. God called the light 'day,' and the darkness he called 'night.' And there was evening, and there was morning—the first day.",
        "It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known.",
        "Two households, both alike in dignity, in fair Verona, where we lay our scene, from ancient grudge break to new mutiny, where civil blood makes civil hands unclean. From forth the fatal loins of these two foes, a pair of star-cross'd lovers take their life; whose misadventured piteous overthrows do with their death bury their parents' strife. The fearful passage of their death-mark'd love, and the continuance of their parents' rage, which, but their children's end, nought could remove, is now the two hours' traffic of our stage; the which if you with patient ears attend, what here shall miss, our toil shall strive to mend.",
        "All animals are equal, but some animals are more equal than others.",
        "It was a bright cold day in April, and the clocks were striking thirteen. The Ministry of Truth—Minitrue, in Newspeak—was startlingly different from any other object in sight. It was an enormous pyramidal structure of glittering white concrete, soaring up, terrace after terrace, three hundred meters into the air."

    ]
}
